apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    name: toolbox
    vendor: forgerock
spec:
  serviceAccountName: tiller
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: toolbox
    #image:  gcr.io/engineering-devops/toolbox:6.0.0
    image: forgerock/toolbox:6.0.0
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_REPO
      value: "https://github.com/ForgeRock/forgeops-init.git"
    - name: GIT_BRANCH
      value: master
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    - name: platform-config
      mountPath: /opt/forgerock/config
  # Use of downward api. We may use this in future to understand what environment we are running in
  # https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
  - name: platform-config
  # If you want to supply a custom.yaml, comment this next line out:
    emptyDir: {}
    # And replace it with the configMap below
    # You must create the configuration with kubectl create configmap platform-config --from-file=custom.yaml
#    configMap:
#      name: platform-config


