# This is a development version of the toolbox. It mounts a local volume that contains the
# forgeops/ project source code.  You need to mount your local forgeops folder on your laptop:
# cd src/forgeops
# minikube mount .:/forgeops
# You can then exec into the toolbox container. The forgeops files will be mounted at /opt/forgerock/forgeops
# I'd suggest doing any editing or git work outside of the container, on the native laptop O/S
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    name: toolbox
    vendor: forgerock
spec:
  terminationGracePeriodSeconds: 3
  restartPolicy: Never
  containers:
  - name: toolbox
    image: forgerock/toolbox:6.0.0
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_REPO
      value: "https://github.com/ForgeRock/forgeops-init.git"
    - name: GIT_BRANCH
      value: master
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    - name: platform-config
      mountPath: /opt/forgerock/config
    - name: forgeops
      mountPath: /opt/forgerock/forgeops
  # Use of downward api. We may use this in future to understand what environment we are running in
  # From docs:
  # only annotations, labels, name and namespace are supported.
  # See https://kubernetes.io/docs/resources-reference/v1.6/#downwardapivolumefile-v1-core
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
  - name: platform-config
    configMap:
      name: platform-config
  - name: forgeops
    hostPath:
      path: /forgeops


