image:
  repository: gcr.io/forgerock-io/openig
  tag: 6.5.1
  pullPolicy: IfNotPresent

config:
  name: frconfig
  path: /git/config/6.5/cdm/m-cluster/ig 
  strategy: git
  
resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 2000m
    memory: 2Gi

# Tomcat JVM options.
catalinaOpts:  >
  -server -Xms2g -Xmx2g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

replicaCount: 2

