image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.1
  pullPolicy: Always

instance: ctsstore

userstore:
  enabled: false

resources:
  limits:
    memory: 3Gi
  requests:
    memory: 1Gi

storageSize: 20Gi
storageClass: fast

# For JDK 8
opendjJavaArgs: >
  -server -Xms1g -Xmx1g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

# For JDK 11
#opendjJavaArgs: >
#  -server -Xms3g -Xmx3g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA  
#  -XX:MaxGCPauseMillis=100 -verbose:gc -Xlog:gc:/tmp/gc.log


podAntiAffinity: hard

runPostSetupJob: false

replicas: 2

topologyKey: "failure-domain.beta.kubernetes.io/zone"
