image:
  repository: gcr.io/forgerock-io/ds
  #repository: gcr.io/engineering-devops/ds
  tag: 6.5.1
  pullPolicy: Always

gcs:
  enabled: false
  bucket: gs://forgeops/dj-backup/s-cluster

s3:
  enabled: false
  bucket: s3://forgeops/dj-backup/s-cluster  

nfs:
  #server: 10.201.33.74
  server: fs-a05fd9e1.efs.ap-southeast-1.amazonaws.com 
  path: /export

backup:
  pvcName: ds-backup
  storageSize: 20Gi

createPVC: true

slackUrl: undefined
