image:
  repository: gcr.io/forgerock-io/openidm
  #repository: gcr.io/engineering-devops/openidm
  tag: 6.5.1
  pullPolicy: IfNotPresent
  
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# For JDK 8
javaOpts: >
  -server -Xms1g -Xmx1g -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseNUMA 
  -XX:MaxGCPauseMillis=100 -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps 
  -XX:+PrintGCDetails -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -Xloggc:/tmp/gc.log

replicaCount: 1

config:
  name: frconfig
  #path: /git/config/6.5/m-cluster/idm/ds-repo-explicit
  path: /git/config/6.5/default/idm/sync-with-ldap-bidirectional
  strategy: git
