image:
  #repository: gcr.io/engineering-devops/openam
  repository: gcr.io/forgerock-io/openam
  tag: 6.5.1
  pullPolicy: Always
  
resources:
  limits:
    cpu: 2000m
    memory: 3Gi
  requests:
    cpu: 1000m
    memory: 2Gi

catalinaOpts: >
  -server -Xms2g -Xmx2g -XX:+UseG1GC -XX:+UseNUMA -XX:+UseCompressedOops
  -XX:MaxGCPauseMillis=200 -XX:G1MixedGCCountTarget=6 -XX:MetaspaceSize=128m  
  -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal
  -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=70
  -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  -Dcom.sun.identity.util.debug.provider=com.sun.identity.shared.debug.impl.StdOutDebugProvider
  -Dcom.sun.identity.shared.debug.file.format='%PREFIX% %MSG%\\n%STACKTRACE%'
  -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails
  -XX:+PrintPromotionFailure -XX:+PrintAdaptiveSizePolicy -XX:+PrintTenuringDistribution 
  -Xloggc:/tmp/gc.log
